package auth

import (
	"context"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"implodo_backend/config"
	"implodo_backend/store"

	"github.com/gin-gonic/gin"
	"golang.org/x/oauth2"
	"golang.org/x/oauth2/google"
)

// Handler holds dependencies for all auth-related HTTP handlers.
type Handler struct {
	cfg         *config.Config
	oauthConfig *oauth2.Config
	sessions    *store.SessionStore
}

func NewHandler(cfg *config.Config, sessions *store.SessionStore) *Handler {
	return &Handler{
		cfg: cfg,
		oauthConfig: &oauth2.Config{
			ClientID:     cfg.GoogleClientID,
			ClientSecret: cfg.GoogleClientSecret,
			RedirectURL:  cfg.GoogleRedirectURL,
			Scopes:       []string{"openid", "profile", "email"},
			Endpoint:     google.Endpoint,
		},
		sessions: sessions,
	}
}

// --- Request/response types ---

type StartRequest struct {
	// State is a random value generated by the app — used to correlate the session.
	// Generate with: crypto/rand, base64url-encode ~16 bytes.
	State string `json:"state" binding:"required"`

	// CodeChallenge is BASE64URL(SHA256(code_verifier)).
	// The app generates a random code_verifier locally and sends only the challenge here.
	// The verifier is never transmitted until the final token exchange.
	CodeChallenge string `json:"code_challenge" binding:"required"`
}

type StartResponse struct {
	// AuthURL is the Google OAuth consent page. Open this in the device browser.
	AuthURL string `json:"auth_url"`
}

type TokenRequest struct {
	// State must match what was sent to /auth/start.
	State string `json:"state" binding:"required"`

	// CodeVerifier is the raw secret from which CodeChallenge was derived.
	// BASE64URL(SHA256(code_verifier)) must equal the stored challenge.
	CodeVerifier string `json:"code_verifier" binding:"required"`
}

type TokenResponse struct {
	Token string `json:"token"`
}

// googleUserInfo is the relevant subset of the response from Google's userinfo endpoint.
type googleUserInfo struct {
	Sub   string `json:"sub"` // Stable Google user ID — this is what we check against AllowedGoogleIDs
	Email string `json:"email"`
	Name  string `json:"name"`
}

// --- Handlers ---

// Start godoc
//
//	POST /auth/start
//
// The app calls this to kick off the auth flow. Returns a Google OAuth URL for the app to open
// in the device browser. The app must supply a state and code_challenge (PKCE-style).
func (h *Handler) Start(c *gin.Context) {
	var req StartRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "state and code_challenge are required"})
		return
	}

	h.sessions.Create(req.State, req.CodeChallenge)

	// We embed the app-supplied state directly so Google echoes it back in the callback.
	// access_type=offline requests a refresh token (optional, remove if not needed).
	authURL := h.oauthConfig.AuthCodeURL(req.State, oauth2.AccessTypeOnline)

	c.JSON(http.StatusOK, StartResponse{AuthURL: authURL})
}

// GoogleCallback godoc
//
//	GET /auth/google/callback
//
// Google redirects here after the user logs in. This endpoint:
//  1. Exchanges the authorization code for Google tokens
//  2. Fetches the user's Google ID and checks it against the allow-list
//  3. Issues a JWT and stores it in the session (keyed by state)
//  4. Redirects the browser to the app's deep link so the app knows to poll /auth/token
func (h *Handler) GoogleCallback(c *gin.Context) {
	state := c.Query("state")
	code := c.Query("code")

	if state == "" || code == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "missing state or code"})
		return
	}

	// Exchange authorization code for Google OAuth tokens.
	oauthToken, err := h.oauthConfig.Exchange(context.Background(), code)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "failed to exchange code"})
		return
	}

	// Fetch user info using the access token.
	userInfo, err := h.fetchGoogleUserInfo(oauthToken)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch user info"})
		return
	}

	// Check whether this Google user is allowed.
	if !h.isAllowed(userInfo.Sub) {
		fmt.Println(userInfo.Sub)
		c.JSON(http.StatusForbidden, gin.H{"error": "account not authorized"})
		return
	}

	// Issue a JWT for this user.
	jwtStr, err := issueJWT(h.cfg, userInfo.Sub, userInfo.Email, userInfo.Name)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to issue token"})
		return
	}

	// Store the JWT in the session — the app will retrieve it via /auth/token.
	if !h.sessions.SetJWT(state, jwtStr) {
		// Session expired or state was never registered — don't issue the token.
		c.JSON(http.StatusBadRequest, gin.H{"error": "unknown or expired state"})
		return
	}

	// Redirect the browser to the app's deep link.
	// The app intercepts this URI and knows to call POST /auth/token.
	deepLink := fmt.Sprintf("%s?state=%s", h.cfg.AppDeepLinkURI, state)
	c.Redirect(http.StatusFound, deepLink)
}

// ExchangeToken godoc
//
//	POST /auth/token
//
// The app calls this after the browser has completed the OAuth flow.
// Returns 202 if auth hasn't completed yet (app should retry).
// Returns 200 with the JWT on success — the JWT is deleted from the store after retrieval.
func (h *Handler) ExchangeToken(c *gin.Context) {
	var req TokenRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "state and code_verifier are required"})
		return
	}

	session, ok := h.sessions.GetAndDelete(req.State)
	if !ok {
		c.JSON(http.StatusNotFound, gin.H{"error": "session not found or expired"})
		return
	}

	// Auth hasn't completed yet — put the session back and tell the app to retry.
	if session.JWT == "" {
		h.sessions.Create(req.State, session.CodeChallenge)
		c.JSON(http.StatusAccepted, gin.H{"status": "pending"})
		return
	}

	// Verify the code_verifier: BASE64URL(SHA256(verifier)) must match the stored challenge.
	if !verifyCodeChallenge(req.CodeVerifier, session.CodeChallenge) {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "invalid code_verifier"})
		return
	}

	// Session is consumed — JWT is returned exactly once.
	c.JSON(http.StatusOK, TokenResponse{Token: session.JWT})
}

// Me godoc
//
//	GET /api/me  (protected)
//
// Returns the authenticated user's info extracted from the JWT.
func (h *Handler) Me(c *gin.Context) {
	claims := GetClaims(c)
	c.JSON(http.StatusOK, gin.H{
		"google_id": claims.GoogleID,
		"email":     claims.Email,
		"name":      claims.Name,
		"expires":   claims.ExpiresAt,
	})
}

// Profile godoc
//
//	GET /api/profile  (protected)
//
// Returns the authenticated user's profile, including their bio description.
func (h *Handler) Profile(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"bio": "I am a lizard making lizard things",
	})
}

// --- Helpers ---

func (h *Handler) fetchGoogleUserInfo(token *oauth2.Token) (*googleUserInfo, error) {
	client := h.oauthConfig.Client(context.Background(), token)
	resp, err := client.Get("https://www.googleapis.com/oauth2/v3/userinfo")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	var info googleUserInfo
	if err := json.Unmarshal(body, &info); err != nil {
		return nil, err
	}
	return &info, nil
}

func (h *Handler) isAllowed(googleID string) bool {
	for _, id := range h.cfg.AllowedGoogleIDs {
		if id == googleID {
			return true
		}
	}
	return false
}

// verifyCodeChallenge checks BASE64URL(SHA256(verifier)) == challenge.
// Uses constant-time comparison to avoid timing attacks.
func verifyCodeChallenge(verifier, challenge string) bool {
	h := sha256.Sum256([]byte(verifier))
	computed := base64.RawURLEncoding.EncodeToString(h[:])
	return subtle.ConstantTimeCompare([]byte(computed), []byte(challenge)) == 1
}
